### ISSUE TITLE
Picard Client Launch Issue

### ISSUE THREAD

**Issue by Rautmare-Sneha** [LUMIA-Group/rasat#16]
Hi

I am executing the Eval code on the spider data with picard using docker image 

1. provided 777 permission to mentioned 2 directories
2. 'make eval' 
3. inside docker -> Install stanza package
4. python3 seq2seq/eval_run_seq2seq.py configs/spider/eval_spider_rasat_4160.json

After preprocessing , generating relation i got following error : 

`
Use relation model.
Traceback (most recent call last):
  File "seq2seq/eval_run_seq2seq.py", line 309, in <module>
    main()
  File "seq2seq/eval_run_seq2seq.py", line 197, in main
    model = model_cls_wrapper(T5ForConditionalGeneration).from_pretrained(
  File "seq2seq/eval_run_seq2seq.py", line 184, in <lambda>
    model_cls=model_cls, picard_args=picard_args, tokenizer=tokenizer, schemas=dataset_splits.schemas
  File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 482, in with_picard
    asyncio.run(_init_picard(), debug=False)
  File "/opt/conda/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 126, in _init_picard
    await _register_schema(db_id=db_id, db_info=db_info, picard_client=client)
  File "/app/seq2seq/utils/custom_picard_model_wrapper.py", line 132, in _register_schema
    await picard_client.registerSQLSchema(db_id, sql_schema)
thrift.py3.exceptions.TransportError: (<TransportErrorType.UNKNOWN: 0>, 'Channel is !good()', 0, <TransportOptions.0: 0>)

`

Enviornment : Macbook
It would be really helpful if you can suggest on this : @Monstarrr @JiexingQi @hantek

**Comment by JiexingQi** [comment]
I did not meet this error yet, maybe you can check the PICARD version and ask in the corresponding repo. https://github.com/ServiceNow/picard
