### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by prattsoroco** [LUMIA-Group/rasat#19]
Getting an error while running `bash run_corefer_processing.sh`
`Start coref process
2023-06-13 08:13:23 INFO: Loading these models for language: en (English):
========================
| Processor | Package  |
------------------------
| tokenize  | combined |
========================

2023-06-13 08:13:23 INFO: Use device: cpu
2023-06-13 08:13:23 INFO: Loading: tokenize
2023-06-13 08:13:23 INFO: Done loading processors!
Traceback (most recent call last):
  File "/home/prathamesh/code/T2S_model_training/rasat/get_coref.py", line 303, in <module>
    get_coref_by_path(input_path = args.input_path, output_path = args.output_path, dataset_name = args.dataset_name, mode = args.mode)
  File "/home/prathamesh/code/T2S_model_training/rasat/get_coref.py", line 285, in get_coref_by_path
    nlp = init_nlp()
  File "/home/prathamesh/code/T2S_model_training/rasat/get_coref.py", line 38, in init_nlp
    nlp = spacy.load('en_core_web_trf')
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/util.py", line 321, in load_model
    return load_model_from_package(name, **kwargs)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/util.py", line 354, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/en_core_web_trf/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/util.py", line 514, in load_model_from_init_py
    return load_model_from_path(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/util.py", line 389, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/util.py", line 426, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/language.py", line 1715, in from_config
    nlp.add_pipe(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/language.py", line 777, in add_pipe
    pipe_component = self.create_pipe(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/spacy/language.py", line 661, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/thinc/config.py", line 746, in resolve
    resolved, _ = cls._make(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/thinc/config.py", line 795, in _make
    filled, _, resolved = cls._fill(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/thinc/config.py", line 850, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/thinc/config.py", line 849, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/site-packages/thinc/config.py", line 1057, in make_promise_schema
    return create_model("ArgModel", **sig_args)
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "/home/prathamesh/anaconda3/envs/coreferee/lib/python3.9/typing.py", line 847, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`

**Comment by JiexingQi** [comment]
Hi @prattsoroco , I did not meet this error yet, I think maybe you can check the spacy version
